### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cole-brokamp**
Let's be consistent on enumeration items and only use one of dots, letters, or roman numerals.

Does the github repository have to be in the CCHMC-SALT organization, right?

### CODE REVIEW

**Comment by cole-brokamp** [comment]
The manifest file has to be created _prior_ to the deploy on SALT.

**Comment by cole-brokamp** [comment]
Instead of deleting [dev] branch, they could keep it open for the next development version (but this would incur costs)

**Comment by cole-brokamp** [comment]
for publishing options, let's point to the existing connect documentation instead of including it ourselves.

**Review by andrew-vancil — APPROVED** [review]
I think we're looking pretty good now. Feel free to take another look through here and I can merge it back in. Thanks!

**Pull request merged**
